# Generated by Django 5.2.11 on 2026-03-04 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('department', models.CharField(choices=[('ALBARDON', 'Albardón'), ('ANGACO', 'Angaco'), ('CALINGASTA', 'Calingasta'), ('CAPITAL', 'Capital'), ('CAUCETE', 'Caucete'), ('CHIMBAS', 'Chimbas'), ('IGLESIA', 'Iglesia'), ('JACHAL', 'Jáchal'), ('9DEJULIO', '9 de Julio'), ('POCITO', 'Pocito'), ('RAWSON', 'Rawson'), ('RIVADAVIA', 'Rivadavia'), ('SANMARTIN', 'San Martín'), ('SANTA_LUCIA', 'Santa Lucía'), ('SARMIENTO', 'Sarmiento'), ('ULLUM', 'Ullum'), ('VALLE_FERTIL', 'Valle Fértil'), ('25DEMAYO', '25 de Mayo'), ('ZONDA', 'Zonda')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_main', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
